### PR TITLE
fullPath option to generate config with full image path

### PR DESCRIPTION
**Pull request by martinhoefling**
Useful if the images are not layed out in a flat directory.

### CODE REVIEW

**Comment by martinhoefling** [comment]
@mahnunchik any chance to get this merged?

**Comment by mahnunchik** [comment]
Done! Sorry for the delay 😢

**Comment by mahnunchik** [comment]
Published https://www.npmjs.com/package/gulp-responsive-config

**Comment by martinhoefling** [comment]
No worries and thx, just went through my open pull requests :+1:

**Pull request merged**
